social_networks:
#  twitter:
#    key: "UHMTtoPCi6Ej3aLpzOHQ"
#    secret: "BmtX68Wbo7PKjHcxZHi34xjV8OG1ZEwbXnvqbA1Ao"
  facebook:
    key: "674280899350070"                       # voyagex.info.tm
    secret: "8e16f4cc6ae9749f08b45601bb4bbe8b"
#    key: "663353313797273"                       # voyagex-local.info.tm:8080
#    secret: "fce020bdf1f5ea03577a710bb2f69707"
